# Generated by Django 5.2.12 on 2026-04-04 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDZSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('weather_score', models.FloatField(default=0)),
                ('order_drop_score', models.FloatField(default=0)),
                ('peer_activity_score', models.FloatField(default=0)),
                ('driver_activity_score', models.FloatField(default=0)),
                ('traffic_score', models.FloatField(default=0)),
                ('final_edz_score', models.FloatField(default=0)),
                ('threshold_breached', models.BooleanField(default=False)),
                ('shadow_only', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edz_snapshots', to='users.zone')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rainfall_mm', models.FloatField(default=0)),
                ('wind_speed_ms', models.FloatField(default=0)),
                ('aqi', models.FloatField(default=0)),
                ('temperature_c', models.FloatField(default=25)),
                ('source_owm', models.BooleanField(default=False)),
                ('source_acw', models.BooleanField(default=False)),
                ('source_imd', models.BooleanField(default=False)),
                ('consensus_confirmed', models.BooleanField(default=False)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='users.zone')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
    ]
