# Generated by Django 5.2.12 on 2026-04-04 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='queued', max_length=15)),
                ('razorpay_transfer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('batch_number', models.IntegerField(default=1)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='claims.claim')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='users.driver')),
            ],
            options={
                'ordering': ['-queued_at'],
            },
        ),
    ]
