# Generated by Django 5.2.12 on 2026-04-04 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Full', 'Full')], max_length=20, unique=True)),
                ('weekly_premium', models.DecimalField(decimal_places=2, max_digits=8)),
                ('daily_payout_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_coverage_days', models.IntegerField()),
                ('reserve_contribution_rate', models.DecimalField(decimal_places=4, default=0.1, max_digits=5)),
                ('seasonal_multiplier', models.FloatField(default=1.0)),
                ('platform_cofund_optional', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DriverPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('last_premium_paid_at', models.DateTimeField(auto_now_add=True)),
                ('last_claim_at', models.DateTimeField(blank=True, null=True)),
                ('reclaim_blocked_until', models.DateTimeField(blank=True, null=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='users.driver')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_policies', to='policies.policyplan')),
            ],
        ),
        migrations.CreateModel(
            name='ReserveWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ever_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=10)),
                ('last_credited_at', models.DateTimeField(auto_now_add=True)),
                ('last_debited_at', models.DateTimeField(blank=True, null=True)),
                ('forfeited_on_cancel', models.BooleanField(default=False)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='users.driver')),
            ],
        ),
    ]
