# Generated by Django 5.2.12 on 2026-04-04 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pool_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('risk_score', models.FloatField(default=0.0)),
                ('active_driver_count', models.IntegerField(default=0)),
                ('max_cross_subsidy', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='users.city')),
            ],
            options={
                'unique_together': {('name', 'city')},
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('aadhaar_hash', models.CharField(max_length=64, unique=True)),
                ('pan_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('device_fingerprint', models.CharField(max_length=512)),
                ('months_active', models.IntegerField(default=0)),
                ('last_beacon_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='users.city')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='users.zone')),
            ],
        ),
        migrations.CreateModel(
            name='DriverActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gps_lat', models.FloatField()),
                ('gps_lng', models.FloatField()),
                ('gps_spoofing_flag', models.BooleanField(default=False)),
                ('accelerometer_active', models.BooleanField(default=False)),
                ('gyro_active', models.BooleanField(default=False)),
                ('network_type', models.CharField(choices=[('4G', '4G'), ('WiFi', 'WiFi'), ('3G', '3G'), ('offline', 'Offline')], default='4G', max_length=10)),
                ('app_in_foreground', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.driver')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['driver', 'timestamp'], name='users_drive_driver__7d4aee_idx'), models.Index(fields=['timestamp'], name='users_drive_timesta_d78d12_idx')],
            },
        ),
    ]
