# Generated by Django 4.2.11 on 2026-04-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='platform_id',
            field=models.CharField(default='', help_text='Shared platform ID from Zomato / Swiggy / other gig platforms', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
