# Generated by Django 5.2.12 on 2026-04-04 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
        ('policies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_fraud_check', 'Pending Fraud Check'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending_fraud_check', max_length=30)),
                ('fraud_score', models.FloatField(default=0)),
                ('cluster_fraud_flag', models.BooleanField(default=False)),
                ('gps_spoof_flag', models.BooleanField(default=False)),
                ('intent_score', models.FloatField(default=0)),
                ('days_covered', models.IntegerField(default=0)),
                ('base_payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wallet_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='users.driver')),
                ('edz_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='monitoring.edzsnapshot')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='policies.driverpolicy')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='users.zone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
